version: '3.8'

services:
  user-service:
    image: ${USER_REPO}:latest
    container_name: user-service
    ports:
      - "5001:5000"
    restart: always

  orders-service:
    image: ${ORDERS_REPO}:latest
    container_name: orders-service
    ports:
      - "5002:5000"
    restart: always

  inventory-service:
    image: ${INVENTORY_REPO}:latest
    container_name: inventory-service
    ports:
      - "5003:5000"
    restart: always
